package isolation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SetupNamespaceDNS creates the resolver configuration for the network namespace.
// On Linux, `ip netns exec <ns>` automatically checks `/etc/netns/<ns>/resolv.conf`.
func SetupNamespaceDNS(namespace string, dnsServers string) error {
	if dnsServers == "" {
		dnsServers = "1.1.1.1, 1.0.0.1"
	}

	netnsEtcDir := filepath.Join("/etc/netns", namespace)
	// Try creating /etc/netns/<ns>/ directory (requires root/CAP_NET_ADMIN)
	if err := os.MkdirAll(netnsEtcDir, 0755); err == nil {
		resolvPath := filepath.Join(netnsEtcDir, "resolv.conf")
		var content strings.Builder
		content.WriteString("# Generated by SkipTUI\n")
		for _, s := range strings.Split(dnsServers, ",") {
			trimmed := strings.TrimSpace(s)
			if trimmed != "" {
				content.WriteString(fmt.Sprintf("nameserver %s\n", trimmed))
			}
		}
		content.WriteString("options edns0 timeout:2 attempts:3\n")
		_ = os.WriteFile(resolvPath, []byte(content.String()), 0644)
	}

	return nil
}

// CleanupNamespaceDNS removes `/etc/netns/<ns>` directory if created.
func CleanupNamespaceDNS(namespace string) {
	_ = os.RemoveAll(filepath.Join("/etc/netns", namespace))
}

// SanitizeProcessEnv strips out D-Bus and host resolver variables to prevent DNS escape.
func SanitizeProcessEnv(initialEnv []string) []string {
	var clean []string
	stripPrefixes := []string{
		"DBUS_SESSION_BUS_ADDRESS=",
		"DBUS_SYSTEM_BUS_ADDRESS=",
		"DBUS_STARTER_ADDRESS=",
		"DBUS_STARTER_BUS_TYPE=",
	}

	for _, env := range initialEnv {
		skip := false
		for _, prefix := range stripPrefixes {
			if strings.HasPrefix(env, prefix) {
				skip = true
				break
			}
		}
		if !skip {
			clean = append(clean, env)
		}
	}

	// Explicitly unset them inside the child process
	clean = append(clean, "DBUS_SESSION_BUS_ADDRESS=")
	clean = append(clean, "DBUS_SYSTEM_BUS_ADDRESS=")

	return clean
}
