package isolation

import (
	"fmt"
	"os"
	"path/filepath"
	"skiptui/internal/config"
	"strings"
)

// SetupNamespaceDNS creates the resolver configuration for the network namespace.
// On Linux, `ip netns exec <ns>` automatically checks `/etc/netns/<ns>/resolv.conf`.
func SetupNamespaceDNS(namespace string, dnsServers string) error {
	if dnsServers == "" {
		dnsServers = "1.1.1.1, 1.0.0.1"
	}

	var content strings.Builder
	content.WriteString("# Generated by SkipTUI\n")
	for _, s := range strings.Split(dnsServers, ",") {
		trimmed := strings.TrimSpace(s)
		if trimmed != "" {
			content.WriteString(fmt.Sprintf("nameserver %s\n", trimmed))
		}
	}
	content.WriteString("options edns0 timeout:2 attempts:3\n")
	resolvData := []byte(content.String())

	// 1. Try creating /etc/netns/<ns>/ directory (if root/privileged)
	netnsEtcDir := filepath.Join("/etc/netns", namespace)
	if err := os.MkdirAll(netnsEtcDir, 0755); err == nil {
		resolvPath := filepath.Join(netnsEtcDir, "resolv.conf")
		_ = os.WriteFile(resolvPath, resolvData, 0644)
	}

	// 2. Also write to XDG runtime directory for user-space reference
	runDir := filepath.Join(config.GetRuntimeDir(), namespace)
	if err := os.MkdirAll(runDir, 0700); err == nil {
		_ = os.WriteFile(filepath.Join(runDir, "resolv.conf"), resolvData, 0600)
	}

	return nil
}

// CleanupNamespaceDNS removes `/etc/netns/<ns>` and runtime config directory.
func CleanupNamespaceDNS(namespace string) {
	_ = os.RemoveAll(filepath.Join("/etc/netns", namespace))
	_ = os.RemoveAll(filepath.Join(config.GetRuntimeDir(), namespace))
}

// SanitizeProcessEnv strips out D-Bus and host resolver variables to prevent DNS escape.
func SanitizeProcessEnv(initialEnv []string) []string {
	var clean []string
	stripPrefixes := []string{
		"DBUS_SESSION_BUS_ADDRESS=",
		"DBUS_SYSTEM_BUS_ADDRESS=",
		"DBUS_STARTER_ADDRESS=",
		"DBUS_STARTER_BUS_TYPE=",
	}

	for _, env := range initialEnv {
		skip := false
		for _, prefix := range stripPrefixes {
			if strings.HasPrefix(env, prefix) {
				skip = true
				break
			}
		}
		if !skip {
			clean = append(clean, env)
		}
	}

	// Explicitly unset them inside the child process
	clean = append(clean, "DBUS_SESSION_BUS_ADDRESS=")
	clean = append(clean, "DBUS_SYSTEM_BUS_ADDRESS=")

	return clean
}
